[package]
name = "laim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.9", features = ["js"] }
gloo-storage = "0.2.2"
js-sys = "0.3.63"
leptos = { git = "https://github.com/leptos-rs/leptos", rev = "2d418dae9342073bd01f4d817bff894e1c7d5fd6" }
rand = "0.8.5"
serde = "1.0.163"
serde_json = "1.0.96"
stylers = "0.3.1"
wasm-bindgen = "0.2.86"
web-sys = { version = "0.3.63", features = ["Document", "MouseEvent", "NamedNodeMap", "Attr", "EventTarget"] }
web-time = "0.2.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
